# Database Configuration
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_auth
spring.datasource.username=postgres
spring.datasource.password=sanjeev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# App Properties
portfolio.app.jwtSecret=portfolioSecretKeyWithEnoughEntropyForHMACSHA256
portfolio.app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=DEBUG
